name: geoana-test
channels:
  - conda-forge
dependencies:
  - numpy>=2.0.0rc1
  - scipy>=1.12
  - libdlf

  # optionals
  - matplotlib-base
  - utm

  # documentation
  - sphinx==8.1.3
  - pydata-sphinx-theme==0.16.1
  - sphinx-gallery==0.19.0
  - numpydoc==1.9.0
  - jupyter
  - graphviz
  - pillow

  # testing
  - pytest
  - pytest-cov
  - sympy

  # Building
  - pip
  - meson-python>=0.15.0
  - meson
  - ninja
  - cython>=3.1.0
  - setuptools_scm
  - python-build